### ISSUE TITLE
Google Voice - message box white

### ISSUE THREAD

**Issue by borisjoffe** [Devo7v/UserCSS#7]
The input box for text messages on Google Voice is white.

This CSS seems to fix it:
```css
.gvThreadDetails-messageEntryContainer {
    background: initial;
}
```
